.TH "clarg::argT< T >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clarg::argT< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arglib\&.hpp>\fP
.PP
Inherits \fBclarg::arg_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBargT\fP (const char *arg, const char *desc)"
.br
.ti -1c
.RI "const T & \fBget_value\fP () const "
.br
.ti -1c
.RI "void \fBset_value\fP (const T &v) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T \fBvalue\fP"
.br
.ti -1c
.RI "T \fBdef_value\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class clarg::argT< T >"
The argument template class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
