.TH "dbt::OIDecoder::OIInst" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::OIDecoder::OIInst \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "OIInstType \fBType\fP"
.br
.ti -1c
.RI "uint8_t \fBRS\fP"
.br
.ti -1c
.RI "uint8_t \fBRT\fP"
.br
.ti -1c
.RI "uint8_t \fBRD\fP"
.br
.ti -1c
.RI "uint8_t \fBRV\fP"
.br
.ti -1c
.RI "int16_t \fBImm\fP"
.br
.ti -1c
.RI "uint32_t \fBAddrs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
