.TH "dbt::ITDInterpreter" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::ITDInterpreter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdbt::Interpreter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBITDInterpreter\fP (\fBSyscallManager\fP &SM, \fBRFT\fP &R)"
.br
.ti -1c
.RI "void \fBexecute\fP (\fBMachine\fP &, uint32_t, uint32_t)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
