.TH "dbt::NET" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::NET \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdbt::RFT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNET\fP (\fBManager\fP &M)"
.br
.ti -1c
.RI "void \fBonBranch\fP (\fBdbt::Machine\fP &)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
