.TH "dbt::SyscallManager" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::SyscallManager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdbt::LinuxSyscallManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBgetExitStatus\fP ()"
.br
.ti -1c
.RI "virtual int \fBprocessSyscall\fP (\fBMachine\fP &)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBExitStatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
