.TH "dbt::Timer" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::Timer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstartClock\fP ()"
.br
.ti -1c
.RI "void \fBstopClock\fP ()"
.br
.ti -1c
.RI "void \fBprintReport\fP (std::string Title)"
.br
.ti -1c
.RI "void \fBprintReport\fP (std::string Title, std::ofstream &reportFile)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
