.TH "dbt::QWord" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::QWord \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBasC_\fP [8]"
.br
.ti -1c
.RI "uint32_t \fBasI32_\fP [2]"
.br
.ti -1c
.RI "uint64_t \fBasI_\fP"
.br
.ti -1c
.RI "double \fBasD_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
