.TH "dbt::MRET2" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbt::MRET2 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdbt::RFT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMRET2\fP (\fBManager\fP &M)"
.br
.ti -1c
.RI "uint32_t \fBgetStoredIndex\fP (uint32_t)"
.br
.ti -1c
.RI "uint32_t \fBgetPhase\fP (uint32_t)"
.br
.ti -1c
.RI "bool \fBhasRecorded\fP (uint32_t)"
.br
.ti -1c
.RI "void \fBmergePhases\fP ()"
.br
.ti -1c
.RI "void \fBfinishPhase\fP ()"
.br
.ti -1c
.RI "void \fBonBranch\fP (\fBdbt::Machine\fP &)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
