.TH "ELFIO::Elf32_Phdr" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::Elf32_Phdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf_Word \fBp_type\fP"
.br
.ti -1c
.RI "Elf32_Off \fBp_offset\fP"
.br
.ti -1c
.RI "Elf32_Addr \fBp_vaddr\fP"
.br
.ti -1c
.RI "Elf32_Addr \fBp_paddr\fP"
.br
.ti -1c
.RI "Elf_Word \fBp_filesz\fP"
.br
.ti -1c
.RI "Elf_Word \fBp_memsz\fP"
.br
.ti -1c
.RI "Elf_Word \fBp_flags\fP"
.br
.ti -1c
.RI "Elf_Word \fBp_align\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
