.TH "ELFIO::Elf64_Shdr" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::Elf64_Shdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf_Word \fBsh_name\fP"
.br
.ti -1c
.RI "Elf_Word \fBsh_type\fP"
.br
.ti -1c
.RI "Elf_Xword \fBsh_flags\fP"
.br
.ti -1c
.RI "Elf64_Addr \fBsh_addr\fP"
.br
.ti -1c
.RI "Elf64_Off \fBsh_offset\fP"
.br
.ti -1c
.RI "Elf_Xword \fBsh_size\fP"
.br
.ti -1c
.RI "Elf_Word \fBsh_link\fP"
.br
.ti -1c
.RI "Elf_Word \fBsh_info\fP"
.br
.ti -1c
.RI "Elf_Xword \fBsh_addralign\fP"
.br
.ti -1c
.RI "Elf_Xword \fBsh_entsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
