.TH "ELFIO::get_sym_and_type< Elf32_Rel >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::get_sym_and_type< Elf32_Rel > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBget_r_sym\fP (Elf_Xword info)"
.br
.ti -1c
.RI "static int \fBget_r_type\fP (Elf_Xword info)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
