.TH "ELFIO::Elf64_Dyn" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::Elf64_Dyn \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf_Sxword \fBd_tag\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   Elf_Xword \fBd_val\fP"
.br
.ti -1c
.RI "   Elf64_Addr \fBd_ptr\fP"
.br
.ti -1c
.RI "} \fBd_un\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
