.TH "ELFIO::Elf32_Ehdr" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::Elf32_Ehdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBe_ident\fP [EI_NIDENT]"
.br
.ti -1c
.RI "Elf_Half \fBe_type\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_machine\fP"
.br
.ti -1c
.RI "Elf_Word \fBe_version\fP"
.br
.ti -1c
.RI "Elf32_Addr \fBe_entry\fP"
.br
.ti -1c
.RI "Elf32_Off \fBe_phoff\fP"
.br
.ti -1c
.RI "Elf32_Off \fBe_shoff\fP"
.br
.ti -1c
.RI "Elf_Word \fBe_flags\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_ehsize\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_phentsize\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_phnum\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_shentsize\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_shnum\fP"
.br
.ti -1c
.RI "Elf_Half \fBe_shstrndx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
