.TH "ELFIO::string_section_accessor" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::string_section_accessor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstring_section_accessor\fP (\fBsection\fP *section_)"
.br
.ti -1c
.RI "const char * \fBget_string\fP (Elf_Word index) const "
.br
.ti -1c
.RI "Elf_Word \fBadd_string\fP (const char *str)"
.br
.ti -1c
.RI "Elf_Word \fBadd_string\fP (const std::string &str)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
