.TH "ELFIO::elf_header_impl_types< Elf64_Ehdr >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::elf_header_impl_types< Elf64_Ehdr > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBElf64_Phdr\fP \fBPhdr_type\fP"
.br
.ti -1c
.RI "typedef \fBElf64_Shdr\fP \fBShdr_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const unsigned char \fBfile_class\fP = ELFCLASS64"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
