.TH "ELFIO::Elf32_Sym" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::Elf32_Sym \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf_Word \fBst_name\fP"
.br
.ti -1c
.RI "Elf32_Addr \fBst_value\fP"
.br
.ti -1c
.RI "Elf_Word \fBst_size\fP"
.br
.ti -1c
.RI "unsigned char \fBst_info\fP"
.br
.ti -1c
.RI "unsigned char \fBst_other\fP"
.br
.ti -1c
.RI "Elf_Half \fBst_shndx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
