.TH "ELFIO::endianess_convertor" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::endianess_convertor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP (unsigned char elf_file_encoding)"
.br
.ti -1c
.RI "uint64_t \fBoperator()\fP (uint64_t value) const "
.br
.ti -1c
.RI "int64_t \fBoperator()\fP (int64_t value) const "
.br
.ti -1c
.RI "uint32_t \fBoperator()\fP (uint32_t value) const "
.br
.ti -1c
.RI "int32_t \fBoperator()\fP (int32_t value) const "
.br
.ti -1c
.RI "uint16_t \fBoperator()\fP (uint16_t value) const "
.br
.ti -1c
.RI "int16_t \fBoperator()\fP (int16_t value) const "
.br
.ti -1c
.RI "int8_t \fBoperator()\fP (int8_t value) const "
.br
.ti -1c
.RI "uint8_t \fBoperator()\fP (uint8_t value) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
