.TH "ELFIO::Elf32_Rel" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::Elf32_Rel \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf32_Addr \fBr_offset\fP"
.br
.ti -1c
.RI "Elf_Word \fBr_info\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
