.TH "ELFIO::elfio::Sections" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ELFIO::elfio::Sections \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSections\fP (\fBelfio\fP *parent_)"
.br
.ti -1c
.RI "Elf_Half \fBsize\fP () const "
.br
.ti -1c
.RI "\fBsection\fP * \fBoperator[]\fP (unsigned int index) const "
.br
.ti -1c
.RI "\fBsection\fP * \fBoperator[]\fP (const std::string &name) const "
.br
.ti -1c
.RI "\fBsection\fP * \fBadd\fP (const std::string &name)"
.br
.ti -1c
.RI "std::vector< \fBsection\fP * >::iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "std::vector< \fBsection\fP * >::iterator \fBend\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
