.TH "spp_rc" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_rc \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBspp_rc\fP (const \fBspp_rc\fP &)"
.br
.ti -1c
.RI "void \fBincrement\fP () const "
.br
.ti -1c
.RI "void \fBdecrement\fP () const "
.br
.ti -1c
.RI "unsigned \fBcount\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
