.TH "spp_::sparsetable< T, Alloc >::GrpPos" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_::sparsetable< T, Alloc >::GrpPos \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBsparsetable::ne_iterator\fP \fBne_iter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGrpPos\fP (const \fBsparsetable\fP &table, size_type i)"
.br
.ti -1c
.RI "bool \fBtest_strict\fP () const "
.br
.ti -1c
.RI "bool \fBtest\fP () const "
.br
.ti -1c
.RI "sparsetable::reference \fBunsafe_get\fP () const "
.br
.ti -1c
.RI "\fBne_iter\fP \fBget_iter\fP (typename sparsetable::reference ref)"
.br
.ti -1c
.RI "void \fBerase\fP (\fBsparsetable\fP &table)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
