.TH "spp_::is_integral< char >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_::is_integral< char > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspp_::integral_constant< T, v >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
