.TH "spp_::integral_constant< T, v >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_::integral_constant< T, v > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBspp_::is_floating_point< T >\fP, \fBspp_::is_floating_point< double >\fP, \fBspp_::is_floating_point< float >\fP, \fBspp_::is_floating_point< long double >\fP, \fBspp_::is_integral< T >\fP, \fBspp_::is_integral< bool >\fP, \fBspp_::is_integral< char >\fP, \fBspp_::is_integral< int >\fP, \fBspp_::is_integral< long >\fP, \fBspp_::is_integral< short >\fP, \fBspp_::is_integral< signed char >\fP, \fBspp_::is_integral< unsigned char >\fP, \fBspp_::is_integral< unsigned int >\fP, \fBspp_::is_integral< unsigned long >\fP, \fBspp_::is_integral< unsigned short >\fP, \fBspp_::is_pointer< T >\fP, \fBspp_::is_pointer< T * >\fP, \fBspp_::is_reference< T >\fP, \fBspp_::is_reference< T & >\fP, \fBspp_::is_relocatable< HashObject< S, H > >\fP, \fBspp_::is_same< T, U >\fP, and \fBspp_::is_same< T, T >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const T \fBvalue\fP = v"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
