.TH "spp_::spp_hash< bool >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_::spp_hash< bool > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits unary_function< bool, size_t >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "SPP_INLINE size_t \fBoperator()\fP (bool __v) const SPP_NOEXCEPT"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
