.TH "spp::malloc_chunk" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp::malloc_chunk \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspp::malloc_chunk_header\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_free_with_pinuse\fP (size_t s, \fBmalloc_chunk\fP *n)"
.br
.ti -1c
.RI "size_t \fBoverhead_for\fP ()"
.br
.ti -1c
.RI "bool \fBcalloc_must_clear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmalloc_chunk\fP * \fB_fd\fP"
.br
.ti -1c
.RI "struct \fBmalloc_chunk\fP * \fB_bk\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
