.TH "spp_::Two_d_destructive_iterator< T, row_it, col_it, iter_type, Alloc >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_::Two_d_destructive_iterator< T, row_it, col_it, iter_type, Alloc > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspp_::Two_d_iterator< T, row_it, col_it, iter_type >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBTwo_d_destructive_iterator\fP \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwo_d_destructive_iterator\fP (Alloc &alloc, row_it curr)"
.br
.ti -1c
.RI "void \fBadvance_past_end\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
