.TH "spp::Timer< time_unit >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp::Timer< time_unit > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBsnap\fP ()"
.br
.ti -1c
.RI "float \fBget_total\fP () const "
.br
.ti -1c
.RI "float \fBget_delta\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
