.TH "spp::malloc_segment" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp::malloc_segment \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBis_mmapped_segment\fP ()"
.br
.ti -1c
.RI "bool \fBis_extern_segment\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fB_base\fP"
.br
.ti -1c
.RI "size_t \fB_size\fP"
.br
.ti -1c
.RI "\fBmalloc_segment\fP * \fB_next\fP"
.br
.ti -1c
.RI "flag_t \fB_sflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
