.TH "spp::malloc_tree_chunk" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp::malloc_tree_chunk \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspp::malloc_chunk_header\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmalloc_tree_chunk\fP * \fBleftmost_child\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmalloc_tree_chunk\fP * \fB_fd\fP"
.br
.ti -1c
.RI "\fBmalloc_tree_chunk\fP * \fB_bk\fP"
.br
.ti -1c
.RI "\fBmalloc_tree_chunk\fP * \fB_child\fP [2]"
.br
.ti -1c
.RI "\fBmalloc_tree_chunk\fP * \fB_parent\fP"
.br
.ti -1c
.RI "bindex_t \fB_index\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
