.TH "spp_::sparsehash_internal::pod_serializer< value_type >" 3 "Mon Apr 23 2018" "Version 0.0.1" "OpenISA Dynamic Binary Translator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spp_::sparsehash_internal::pod_serializer< value_type > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename INPUT > bool \fBoperator()\fP (INPUT *fp, value_type *value) const "
.br
.ti -1c
.RI "template<typename OUTPUT > bool \fBoperator()\fP (OUTPUT *fp, const value_type &value) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenISA Dynamic Binary Translator from the source code\&.
